### PR TITLE
Add xdebug pre-dep to circleCI

### LINKED ISSUE #4: Automate tests in CircleCI

### PR DESCRIPTION
**Pull request by j4m3s**
Required to allow automated build/test.  Fixes #4

### CODE REVIEW

**Comment by j4m3s** [comment]
@g105b I can't tell for the life of me why phpunit is dying on circleci.  Any ideas?

**Comment by j4m3s** [comment]
Fixed circleci - told it not to run the coverage.  They're run on scrutinizer so no need to run them on circleCI too.

**Comment by g105b** [comment]
What's gone wrong with Scrutiniser?

**Comment by g105b** [comment]
Could you tell me why this is necessary to do when the circle yml file is identical to that in the dom repo?

**Comment by j4m3s** [comment]
Because the composer.yaml file in the dom repo is missing the dev-depends
for xdebug.

**Comment by g105b** [comment]
Roger that, hadn't noticed.

**Pull request merged**
